version: 2
jobs:
  build:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run: npm install # check all packages if everything can be installed
      - run: CI=true npm run build

  test:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run: npm install
      - run: npm test

  hithere:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run: echo "hellooo!"

workflows:
  version: 2
  build-test-and-lint:
    jobs:
      - build
      - hithere
      - test:
          requires:
            - hithere
