version: 2
jobs:
  build1:
    docker:
      - image: circleci/node:4.8.2 
    steps:
      - checkout 
      - run: echo "hello world" 

  build2:
    docker:
      - image: circleci/node:4.8.2 
    steps:
      - checkout 
      - run: echo "Double trouble" 

workflows:
  version: 2
  build1_2:
    jobs:
      - build1
      - build2